[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["redis_caching"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "redis_caching"
  org = "chiranfernando"
  version = "3.1.2"

